name: Process and Update Skill Collection

on:
  workflow_dispatch:

jobs:
  process-and-update:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
      with:
        token: ${{ secrets.GH_PAT }} # Use PAT for checkout

    - name: Fetch Skill Collection Data
      run: |
        curl -H 'accept: application/json' -o skillCollection.json "${{ env.SKILL_COLLECTION_URL }}

    - name: Commit and Push Skill Files
      run: |
        git add .
        git diff --staged --quiet || git commit -m "Add/Update Skill Files"
        git push https://${{ secrets.GH_PAT }}@github.com/wgu-skills/cs.git

