name: 'Updater Action'
description: 'Updates collection data and commits changes to the repository.'

inputs:
  skillCollectionSlug:
    description: 'Skill Collection Slug'
    required: true
  skillCollectionUrl:
    description: 'Skill Collection URL'
    required: true
  skillCollectionUuid:
    description: 'Skill Collection UUID'
    required: true
  gitOrg:
    description: 'GitHub Organization'
    required: true
  gitUsername:
    description: 'GitHub Username'
    required: true
  gitEmail:
    description: 'GitHub Email'
    required: true
  patToken:
    description: 'GitHub Personal Access Token'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20'

    - name: Run update script
      run: node dist/index.js
      shell: bash
      env:
        SKILL_COLLECTION_SLUG: ${{ inputs.skillCollectionSlug }}
        SKILL_COLLECTION_URL: ${{ inputs.skillCollectionUrl }}
        SKILL_COLLECTION_UUID: ${{ inputs.skillCollectionUuid }}
        GIT_ORG: ${{ inputs.gitOrg }}
        GIT_USERNAME: ${{ inputs.gitUsername }}
        GIT_EMAIL: ${{ inputs.gitEmail }}
        PAT_TOKEN: ${{ inputs.patToken }}

    - name: Commit and Push changes
      run: |
        git config --local user.email "$GIT_EMAIL"
        git config --local user.name "$GIT_USERNAME"
        git add .
        git commit -m "Update skill collection data" -a || echo "No changes to commit"
        git push
      shell: bash
      env:
        GIT_EMAIL: ${{ inputs.gitEmail }}
        GIT_USERNAME: ${{ inputs.gitUsername }}
