name: 'Updater Action'
description: 'Updates collection data'
inputs:
  skillCollectionUrl:
    description: 'Skill Collection URL'
    required: true
  patToken:
    description: 'Personal Access Token'
    required: true
runs:
  using: 'node16' # or 'composite' if you're running shell commands
  main: 'index.js' # The entry point script
