name: 'Update Skill Collection'
description: 'Updates collection data and commits changes to the repository.'
inputs:
  skillCollectionSlug:
    description: 'Skill Collection Slug'
    required: true
  skillCollectionUrl:
    description: 'Skill Collection URL'
    required: true
  skillCollectionUuid:
    description: 'Skill Collection UUID'
    required: true
  gitOrg:
    description: 'GitHub Organization'
    required: true
  gitUsername:
    description: 'GitHub Username'
    required: true
  gitEmail:
    description: 'GitHub Email'
    required: true
  githubToken:
    description: 'GitHub Token'
    required: true
runs:
  using: 'composite'
  steps:

    - name: Configure Git
      shell: bash
      run: |
        git config --local user.email "${{ inputs.gitEmail }}"
        git config --local user.name "${{ inputs.gitUsername }}"

    - name: Checkout Skill Collection Repo
      uses: actions/checkout@v4
      
    - name: Checkout Updater Repo
      uses: actions/checkout@v4
      with:
        repository: wgu-skills/updater
        path: updater

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Run update script
      shell: bash
      run: node updater/dist/index.js
      env:
        skillCollectionSlug: ${{ inputs.skillCollectionSlug }}
        skillCollectionUrl: ${{ inputs.skillCollectionUrl }}
        skillCollectionUuid: ${{ inputs.skillCollectionUuid }}
        gitOrg: ${{ inputs.gitOrg }}
        gitUsername: ${{ inputs.gitUsername }}
        gitEmail: ${{ inputs.gitEmail }}

    - name: Commit and push if changes
      shell: bash
      run: |
        rm -rf updater
        git add -A
        git diff --staged --exit-code > /dev/null || git commit -m "Automated commit message"
        git push

