name: 'Updater Action'
description: 'Updates collection data'
inputs:
  skillCollectionUrl:
    description: 'Skill Collection URL'
    required: true
  patToken:
    description: 'Personal Access Token'
    required: true
runs:
  using: 'node20'
  main: 'dist/index.js'